import { expect, test } from '@playwright/test';

test('mobile navigation opens, follows a link, and closes', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 800 });
  await page.goto('/');
  await expect(page.locator('#main-sidebar')).toBeHidden();
  await page.getByRole('button', { name: 'Show navigation' }).click();
  await expect(page.locator('#main-sidebar')).toBeVisible();
  await page.locator('#main-sidebar').getByRole('link', { name: 'Archive' }).click();
  await expect(page).toHaveURL(/\/archive$/);
  await expect(page.locator('#main-sidebar')).toBeHidden();
  await page.getByRole('button', { name: 'Show navigation' }).click();
  await page.keyboard.press('Escape');
  await expect(page.locator('#main-sidebar')).toBeHidden();
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Your test workspace' })).toBeVisible();
  await expect(page.getByText('Swipe sideways to see all case columns')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile-workspace.png', fullPage: true });
});

test('create a project, module and multi-step case, then reopen it', async ({ page }) => {
  const projectName = `Browser test ${Date.now()}`;
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Projects', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Archive' })).toBeVisible();
  const projectsPosition = await page.getByRole('button', { name: 'Projects', exact: true }).boundingBox();
  const archivePosition = await page.getByRole('link', { name: 'Archive' }).boundingBox();
  expect(projectsPosition!.y).toBeLessThan(archivePosition!.y);
  await page.getByRole('button', { name: 'Hide navigation' }).click();
  await expect(page.locator('#main-sidebar')).toBeHidden();
  await page.getByRole('button', { name: 'Show navigation' }).click();
  await expect(page.locator('#main-sidebar')).toBeVisible();
  await page.getByRole('button', { name: '+ New project', exact: true }).click();
  let dialog = page.getByRole('dialog');
  await dialog.getByLabel('Name', { exact: false }).fill(projectName);
  await dialog.getByRole('button', { name: 'Save project', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page).toHaveURL(/\/projects\/browser-test-\d+--\d+$/);
  await expect(page.getByRole('heading', { name: 'Recently opened projects' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '+ New project', exact: true })).toHaveCount(0);
  await expect(page.locator('header.page-heading').getByRole('button', { name: 'Delete project' })).toBeVisible();
  await expect(page.getByRole('button', { name: /Projects/ })).not.toContainText('(');

  await page.getByRole('button', { name: '+ New module', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Name', { exact: false }).fill('Authentication');
  await dialog.getByRole('button', { name: 'Save module', exact: true }).click();
  await expect(dialog).not.toBeVisible();

  await page.getByRole('button', { name: '+ New test case', exact: true }).last().click();
  dialog = page.getByRole('dialog');
  // A blank submission must stay on the form and explain the problem.
  await dialog.getByRole('button', { name: 'Save test case', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('required');
  await dialog.getByLabel('Title').fill('Login with valid credentials');
  await dialog
    .getByLabel('Description', { exact: true })
    .fill('A synthetic browser acceptance test.');
  await dialog.getByLabel('Preconditions').fill('An active account exists.');
  await dialog.getByLabel('Action', { exact: false }).fill('Open login');
  await dialog.getByLabel('Expected result', { exact: false }).fill('The login form appears');
  await dialog.getByRole('button', { name: '+ Add step', exact: true }).click();
  await dialog.getByLabel('Action', { exact: false }).nth(1).fill('Submit valid credentials');
  await dialog
    .getByLabel('Expected result', { exact: false })
    .nth(1)
    .fill('The account page appears');
  await dialog.getByRole('button', { name: 'Save test case', exact: true }).click();
  await expect(page).toHaveURL(/\/projects\/browser-test-\d+--\d+\/modules\/authentication--\d+\/cases\/\d+$/);
  await expect(page.getByRole('heading', { name: 'Login with valid credentials' })).toBeVisible();
  await expect(page.locator('.saved-step')).toHaveCount(2);
  await expect(page.locator('.saved-step').first()).toContainText('Open login');
  await expect(page.getByText('mark it Ready before recording Passed/Failed results')).toBeVisible();
  await expect(page.getByRole('checkbox', { name: '✓ Passed' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '✕ Failed' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '+ Add Actions' })).toBeEnabled();
  await page.getByRole('button', { name: 'Mark ready' }).click();
  await expect(page.getByRole('progressbar')).toHaveAttribute('value', '0');
  await page.getByRole('button', { name: 'Next unrecorded step' }).click();
  await expect(page.locator('.saved-step').first()).toBeFocused();
  await page.getByRole('button', { name: 'Remove step 1' }).click();
  const removeDialog = page.getByRole('dialog', { name: 'Remove step 1?' });
  await expect(removeDialog).toBeVisible();
  await removeDialog.getByRole('button', { name: 'Cancel' }).click();
  await expect(page.locator('.saved-step')).toHaveCount(2);
  await page.getByRole('checkbox', { name: '✓ Passed' }).first().check();
  await expect(page.getByRole('progressbar')).toHaveAttribute('value', '1');
  await expect(page.getByText('1 passed · 0 failed · 1 unrecorded')).toBeVisible();
  await page.getByRole('link', { name: `Back to ${projectName}` }).click();
  const unfinishedDialog = page.getByRole('dialog', { name: 'Leave this unfinished run?' });
  await expect(unfinishedDialog).toBeVisible();
  await unfinishedDialog.getByRole('button', { name: 'Cancel' }).click();
  await expect(page.getByRole('heading', { name: 'Login with valid credentials' })).toBeVisible();
  await page.getByRole('button', { name: 'Next unrecorded step' }).click();
  await expect(page.locator('.saved-step').nth(1)).toBeFocused();
  await page.getByRole('button', { name: '✕ Failed' }).nth(1).click();
  const failureDialog = page.getByRole('dialog', { name: 'Actual Result' });
  await expect(failureDialog).toBeVisible();
  await failureDialog.getByLabel('Actual test result').fill('An error page appeared');
  await failureDialog.getByRole('group', { name: 'Can this issue be replicated?' }).getByLabel('Yes').check();
  await failureDialog.getByRole('group', { name: 'Are you the only user affected?' }).getByLabel('No', { exact: true }).check();
  await failureDialog.getByRole('button', { name: 'Record failed step' }).click();
  await page.getByRole('button', { name: 'Save completed run' }).click();
  await expect(page.getByRole('status')).toContainText('Run saved: Failed.');
  await expect(page.locator('.action-state')).toHaveText(['Done', 'Done']);
  await expect(page.getByRole('button', { name: 'Save completed run' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Start another run' }).click();
  await expect(page.getByRole('progressbar')).toHaveAttribute('value', '0');
  await page.reload();
  await expect(page.locator('.saved-step').nth(1)).toContainText('The account page appears');
  await expect(page.getByText('Previous runs')).toBeVisible();
  await expect(page.locator('.run-history')).toHaveCount(1);
  await page.locator('.run-history summary').click();
  await expect(page.locator('.run-history')).toContainText('An error page appeared');
  await page.getByRole('button', { name: 'Edit case' }).click();
  const editDialog = page.getByRole('dialog', { name: 'Edit test case' });
  await editDialog.getByLabel('Description').fill('Updated synthetic acceptance test.');
  await editDialog.getByRole('button', { name: 'Move step 2 up' }).click();
  await editDialog.getByLabel('Action', { exact: false }).first().fill('Submit the login form');
  await editDialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(editDialog).not.toBeVisible();
  await expect(page.locator('.saved-step').first()).toContainText('Submit the login form');
  await expect(page.locator('.run-history')).toContainText('Open login');
  await expect(page.locator('.action-state').first()).toHaveText('Outstanding');
  await page.reload();
  await expect(page.locator('.saved-step').first()).toContainText('Submit the login form');
  await expect(page.locator('.run-history')).toContainText('Open login');
  await page.getByRole('button', { name: '+ Add Actions' }).click();
  const addActionDialog = page.getByRole('dialog', { name: 'Add Action' });
  await addActionDialog.getByRole('button', { name: 'Add Action' }).click();
  await expect(addActionDialog.getByRole('alert')).toContainText('Enter an action');
  await addActionDialog.locator('#new-action').fill('Check the profile page');
  await addActionDialog.locator('#new-expected-result').fill('Profile details appear');
  await addActionDialog.getByRole('button', { name: 'Add Action' }).click();
  await expect(page.locator('.saved-step')).toHaveCount(3);
  await expect(page.locator('.saved-step').last()).toContainText('Check the profile page');
  await expect(page.locator('.action-state').last()).toHaveText('Outstanding');
  await expect(page.locator('.run-history')).toContainText('2 steps');
  await page.getByRole('button', { name: 'Remove step 3' }).click();
  await page.getByRole('dialog', { name: 'Remove step 3?' }).getByRole('button', { name: 'Remove step' }).click();
  await expect(page.locator('.saved-step')).toHaveCount(2);
  await expect(page.getByRole('link', { name: projectName, exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/case-detail.png', fullPage: true });
  await page.getByRole('link', { name: `Back to ${projectName}`, exact: false }).click();
  await expect(page).toHaveURL(/\/projects\/browser-test-\d+--\d+$/);
  await expect(page.locator('.project-overview .outcome-failed strong')).toHaveText('1');
  await expect(page.locator('.project-overview')).toContainText('Latest run failed');
  await expect(page.getByRole('row', { name: /Login with valid credentials/ })).toContainText('Failed');
  await expect(page.getByRole('row', { name: /Login with valid credentials/ })).toContainText('1 run');
  await expect(
    page.getByRole('link', { name: 'Login with valid credentials' }).first(),
  ).toBeVisible();
  const caseSearch = page.getByRole('searchbox', { name: 'Search cases' });
  await caseSearch.fill('no matching title');
  await expect(page.getByRole('heading', { name: 'No matching test cases' })).toBeVisible();
  await caseSearch.fill('valid credentials');
  await expect(page.getByRole('link', { name: 'Login with valid credentials', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Authentication', exact: true }).click();
  await expect(page).toHaveURL(/\?module=\d+$/);
  await expect(page.getByRole('heading', { name: 'Authentication test cases' })).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Module' }))
    .toHaveValue(new URL(page.url()).searchParams.get('module'));
  await page.screenshot({ path: 'test-results/workspace-filtered.png', fullPage: true });
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await expect(page).toHaveURL(/\/projects\/browser-test-\d+--\d+$/);
  const editLink = page.getByRole('link', { name: 'Edit test case Login with valid credentials' });
  await expect(editLink).toBeVisible();
  await editLink.click();
  await expect(page.getByRole('heading', { name: 'Login with valid credentials' })).toBeVisible();
  await page.getByRole('button', { name: 'Remove step 1' }).click();
  await page.getByRole('dialog', { name: 'Remove step 1?' }).getByRole('button', { name: 'Remove step' }).click();
  await expect(page.locator('.saved-step')).toHaveCount(1);
  await page.getByRole('button', { name: 'Delete test case by removing last step' }).click();
  const deleteDialog = page.getByRole('dialog', { name: 'Delete test case?' });
  await expect(deleteDialog).toContainText('all saved run history');
  await expect(deleteDialog.getByRole('button', { name: 'Delete test case' })).toBeDisabled();
  await deleteDialog.getByLabel('Type Confirm to confirm').fill('confirm');
  await expect(deleteDialog.getByRole('button', { name: 'Delete test case' })).toBeDisabled();
  await deleteDialog.getByLabel('Type Confirm to confirm').fill('Confirm');
  await deleteDialog.getByRole('button', { name: 'Delete test case' }).click();
  await expect(page).toHaveURL(/\/projects\/browser-test-\d+--\d+/);
  await expect(page.getByRole('link', { name: 'Login with valid credentials' })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Project test cases' })).toBeVisible();
  await page.screenshot({ path: 'test-results/workspace.png', fullPage: true });
  await page.getByRole('button', { name: 'Delete Module' }).click();
  const moduleConfirmation = page.getByRole('dialog', { name: 'Delete module?' });
  await expect(moduleConfirmation).toContainText('Authentication');
  await moduleConfirmation.getByRole('button', { name: 'Delete module' }).click();
  await expect(page.getByRole('link', { name: 'Authentication', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Modules' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Authentication', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Delete project' }).click();
  const projectConfirmation = page.getByRole('dialog', { name: 'Delete project?' });
  await expect(projectConfirmation).toContainText(projectName);
  await projectConfirmation.getByRole('button', { name: 'Delete project' }).click();
  await expect(page).toHaveURL('/');
  await page.reload();
  await expect(page.getByRole('link', { name: projectName, exact: true })).toHaveCount(0);
});

test('empty projects use an in-app deletion confirmation', async ({ page }) => {
  const name = `Delete check ${Date.now()}`;
  await page.goto('/');
  await page.getByRole('button', { name: '+ New project', exact: true }).click();
  const editor = page.getByRole('dialog', { name: 'Create project' });
  await editor.getByLabel('Name').fill(name);
  await editor.getByRole('button', { name: 'Save project' }).click();
  await expect(page.getByRole('heading', { name })).toBeVisible();
  await page.getByRole('button', { name: 'Delete project' }).click();
  const confirmation = page.getByRole('dialog', { name: 'Delete project?' });
  await expect(confirmation).toContainText(name);
  await confirmation.getByRole('button', { name: 'Cancel' }).click();
  await expect(confirmation).not.toBeVisible();
  await expect(page.getByRole('heading', { name })).toBeVisible();
  await page.getByRole('main').getByRole('button', { name: 'Delete project' }).click();
  await confirmation.getByRole('button', { name: 'Delete project' }).click();
  await expect(page).toHaveURL('/');
  await expect(page.getByRole('link', { name })).toHaveCount(0);
});

test('a saved failed run allows completion, then the case is view-only', async ({ page }) => {
  const projectName = `Complete check ${Date.now()}`;
  await page.goto('/');
  await page.getByRole('button', { name: '+ New project', exact: true }).click();
  let dialog = page.getByRole('dialog', { name: 'Create project' });
  await dialog.getByLabel('Name').fill(projectName);
  await dialog.getByRole('button', { name: 'Save project' }).click();
  await page.getByRole('button', { name: '+ New module' }).click();
  dialog = page.getByRole('dialog', { name: 'Create module' });
  await dialog.getByLabel('Name').fill('Payments');
  await dialog.getByRole('button', { name: 'Save module' }).click();
  await page.getByRole('button', { name: '+ New test case' }).click();
  dialog = page.getByRole('dialog', { name: 'Create test case' });
  await dialog.getByLabel('Title').fill('Card payment');
  await dialog.getByRole('combobox', { name: 'Status' }).selectOption('Ready');
  await dialog.getByLabel('Action', { exact: false }).fill('Submit payment');
  await dialog.getByLabel('Expected result', { exact: false }).fill('Confirmation appears');
  await dialog.getByRole('button', { name: 'Save test case' }).click();

  await expect(page.getByRole('button', { name: 'Mark complete' })).toBeDisabled();
  await page.getByRole('button', { name: '✕ Failed' }).click();
  dialog = page.getByRole('dialog', { name: 'Actual Result' });
  await dialog.getByLabel('Actual test result').fill('Error message appears');
  await dialog.getByRole('group', { name: 'Can this issue be replicated?' }).getByLabel('Unknown').check();
  await dialog.getByRole('group', { name: 'Are you the only user affected?' }).getByLabel('Unknown').check();
  await dialog.getByRole('button', { name: 'Record failed step' }).click();
  await page.getByRole('button', { name: 'Save completed run' }).click();
  await page.locator('.run-history summary').click();
  await expect(page.locator('.run-history')).toContainText('Can this issue be replicated? Unknown');
  await expect(page.getByRole('button', { name: 'Mark complete' })).toBeEnabled();
  await page.getByRole('button', { name: 'Mark complete' }).click();
  await expect(page.locator('.case-heading .badge')).toHaveText('Complete');
  await expect(page.locator('.action-state')).toHaveText('Done');
  await expect(page.getByRole('button', { name: 'Edit case' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '+ Add Actions' })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Delete test case by removing last step' })).toBeDisabled();
  await expect(page.getByRole('button', { name: '✕ Failed' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Save completed run' })).toHaveCount(0);
  await expect(page.locator('.run-history')).toHaveCount(1);
  await page.reload();
  await expect(page.locator('.case-heading .badge')).toHaveText('Complete');
  await expect(page.getByRole('button', { name: '+ Add Actions' })).toBeDisabled();
  const caseUrl = page.url();
  await page.getByRole('link', { name: `Back to ${projectName}` }).click();
  await expect(page.getByRole('columnheader', { name: 'Edit', exact: true })).toBeVisible();
  await expect(page.getByRole('columnheader', { name: 'Archive', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Archive test case Card payment' }).click();
  await page.getByRole('dialog', { name: 'Archive test case?' }).getByRole('button', { name: 'Archive case' }).click();
  await expect(page.getByRole('row', { name: /Card payment/ })).toHaveCount(0);
  await page.getByRole('link', { name: 'Archive' }).click();
  const projectId = caseUrl.match(/\/projects\/[^/]*--(\d+)\/modules\//)?.[1];
  expect(projectId).toBeTruthy();
  await page.getByRole('combobox', { name: 'Project' }).selectOption(projectId!);
  await expect(page.getByRole('row', { name: /Card payment/ })).toContainText('Complete');
  await page.screenshot({ path: 'test-results/archive.png', fullPage: true });
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Export JSON' }).click();
  await expect((await downloadPromise).suggestedFilename()).toMatch(/archived-test-cases-.*\.json/);
  const csvDownloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Export CSV ZIP' }).click();
  await expect((await csvDownloadPromise).suggestedFilename()).toMatch(/archived-test-cases-.*\.zip/);
  await page.getByRole('row', { name: /Card payment/ }).getByRole('button', { name: 'Restore' }).click();
  await page.getByRole('dialog', { name: 'Restore test case?' }).getByRole('button', { name: 'Restore case' }).click();
  await expect(page.getByRole('row', { name: /Card payment/ })).toHaveCount(0);
  await page.goto(caseUrl);
  await expect(page.locator('.case-heading .badge')).toHaveText('Complete');
  await expect(page.locator('.run-history')).toHaveCount(1);
  await page.getByRole('button', { name: 'Delete test case', exact: true }).click();
  const confirmation = page.getByRole('dialog', { name: 'Delete test case?' });
  await confirmation.getByLabel('Type Confirm to confirm').fill('Confirm');
  await confirmation.getByRole('button', { name: 'Delete test case' }).click();
  await expect(page.getByRole('link', { name: 'Card payment' })).toHaveCount(0);
});
