// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestCaseManager.Api.Data;

#nullable disable

namespace TestCaseManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927213116_FailureDetails")]
    partial class FailureDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TestCaseManager.Api.Models.ManualRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("ManualRuns");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.ManualStepResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualResult")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("CanReplicate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ManualRunId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("OnlyUserAffected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalStepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManualRunId");

                    b.ToTable("ManualStepResults");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Preconditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.TestStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId", "Position")
                        .IsUnique();

                    b.ToTable("TestSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_TestSteps_Position", "\"Position\" >= 1");
                        });
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.ManualRun", b =>
                {
                    b.HasOne("TestCaseManager.Api.Models.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.ManualStepResult", b =>
                {
                    b.HasOne("TestCaseManager.Api.Models.ManualRun", "ManualRun")
                        .WithMany("Steps")
                        .HasForeignKey("ManualRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManualRun");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.Module", b =>
                {
                    b.HasOne("TestCaseManager.Api.Models.Project", "Project")
                        .WithMany("Modules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.TestCase", b =>
                {
                    b.HasOne("TestCaseManager.Api.Models.Module", "Module")
                        .WithMany("TestCases")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.TestStep", b =>
                {
                    b.HasOne("TestCaseManager.Api.Models.TestCase", "TestCase")
                        .WithMany("Steps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.ManualRun", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.Module", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.Project", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("TestCaseManager.Api.Models.TestCase", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
